name: "Terraform Lint and Validate"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform Check"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        run: terraform fmt -check -recursive
        # This fails the build if your code isn't pretty!

      - name: Terraform Init & Validate
        run: |
          for dir in day1 day2 day3 day4; do
            if [ -d "$dir" ]; then
              echo "Checking $dir..."
              cd $dir
              terraform init -backend=false
              terraform validate
              cd ..
            fi
          done
